name: "Generate extra info from index"
on:
  schedule:
    - cron: "0 */7 * * *"
  # push:
  #   branches:
  #     - 'main'
  #   paths:
  #     - 'index.json'
  workflow_dispatch:


env:
  PYTHONUNBUFFERED: 1 # ensure that python scripts live output instead of buffering

jobs:
  index-crawl:
    name: index-crawl
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # At this point I'm just taking the piss but we stagger each job cancellation to avoid
          # git pushes being blocked by each other. I have absolutely no idea if this will work
          # but it's funny enough to try.
          - letter: '_special'
            stagger: 5
          - letter: 'a'
            stagger: 10
          - letter: 'b'
            stagger: 15
          - letter: 'c'
            stagger: 20
          - letter: 'd'
            stagger: 25
          - letter: 'e'
            stagger: 30
          - letter: 'f'
            stagger: 35
          - letter: 'g'
            stagger: 40
          - letter: 'h'
            stagger: 45
          - letter: 'i'
            stagger: 50
          - letter: 'j'
            stagger: 55
          - letter: 'k'
            stagger: 60
          - letter: 'l'
            stagger: 65
          - letter: 'm'
            stagger: 70
          - letter: 'n'
            stagger: 75
          - letter: 'o'
            stagger: 80
          - letter: 'p'
            stagger: 85
          - letter: 'q'
            stagger: 90
          - letter: 'r'
            stagger: 95
          - letter: 's'
            stagger: 100
          - letter: 't'
            stagger: 105
          - letter: 'u'
            stagger: 110
          - letter: 'v'
            stagger: 115
          - letter: 'w'
            stagger: 120
          - letter: 'x'
            stagger: 125
          - letter: 'y'
            stagger: 130
          - letter: 'z'
            stagger: 135
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          cache: 'pip'

      - run: pip install -r requirements.txt
        working-directory: scripts

      - run: python platforms.py
        working-directory: scripts

      - run: python index_to_letters.py
        working-directory: scripts
      
      - run: python scrape.py
        working-directory: scripts
        env:
          LETTER: "${{ matrix.letter }}"
      
      # You can take up to 5 minutes to cancel before Github forces a kill
      # https://docs.github.com/en/actions/managing-workflow-runs/canceling-a-workflow#steps-github-takes-to-cancel-a-workflow-run
      - run: sleep ${{ matrix.stagger }}
        if: always()

      - name: Commit changes
        if: always()
        run: |
          set -eux

          git config --local user.email "helper@utf9k.net"
          git config --local user.name "Indexer Bot"
          git config pull.rebase false

          git pull origin main
          git add .
          git commit -a -m "Index extras have been updated" || exit 0
      
      - name: Push changes
        if: always()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
